# Generated by Django 5.2.5 on 2025-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_bid_id_alter_category_id_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
