# Generated by Django 5.2.5 on 2025-08-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_user_id_alter_watchlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bids",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bid",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.comment",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="listing_images"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
    ]
