# Generated by Django 5.2.5 on 2025-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_listing_bids_alter_listing_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
    ]
