# Generated by Django 5.2.5 on 2025-08-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.comment",
            ),
        ),
    ]
