# Generated by Django 5.2.5 on 2025-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_listing_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_images"),
        ),
    ]
