# Generated by Django 5.2.5 on 2025-08-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_listing_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bids",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price",
        ),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.listing",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auctions.category",
            ),
        ),
    ]
